"""FastAPI REST API for the RAG Framework — Phase 6.

Endpoints:
  GET  /health     — liveness probe (no external deps)
  GET  /stats      — Qdrant collection statistics
  POST /upload     — ingest a document (PDF / TXT / MD / HTML)
  POST /search     — hybrid search + cross-encoder reranking
  POST /ask        — full pipeline: retrieval → reranking → cited answer
  POST /stream     — same as /ask but streams tokens via Server-Sent Events

Run locally:
  uvicorn rag.api:app --reload --port 8000

Interactive docs (auto-generated by FastAPI):
  http://localhost:8000/docs   ← Swagger UI
  http://localhost:8000/redoc  ← ReDoc
"""

from __future__ import annotations

import json
import os
import shutil
import tempfile
from pathlib import Path

from fastapi import FastAPI, File, Form, Header, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="RAG Framework API",
    description=(
        "Production RAG pipeline with hybrid BM25 + vector search, "
        "cross-encoder reranking, and inline-cited answer generation."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # tighten to your frontend origin in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Lazy singletons — heavy models (bi-encoder, cross-encoder, LLM client)
# load once on first request, not at import time.
# ---------------------------------------------------------------------------

_embedder  = None
_store     = None
_retriever = None
_reranker  = None
_generator = None


def _get_embedder():
    global _embedder
    if _embedder is None:
        from rag.embeddings import Embedder
        _embedder = Embedder()
    return _embedder


def _get_store():
    global _store
    if _store is None:
        from rag.vectorstore import VectorStore
        _store = VectorStore()
    return _store


def _get_retriever():
    global _retriever
    if _retriever is None:
        from rag.hybrid_retriever import HybridRetriever
        _retriever = HybridRetriever(
            vector_store=_get_store(),
            embedder=_get_embedder(),
        )
    return _retriever


def _get_reranker():
    global _reranker
    if _reranker is None:
        from rag.reranker import Reranker
        _reranker = Reranker()
    return _reranker


def _get_generator():
    global _generator
    if _generator is None:
        from rag.generator import Generator
        _generator = Generator()
    return _generator


# ---------------------------------------------------------------------------
# Request / Response schemas (Pydantic v2)
# ---------------------------------------------------------------------------

class AskRequest(BaseModel):
    query: str
    top_k: int = 5


class SearchRequest(BaseModel):
    query: str
    top_k: int = 5


class SearchResult(BaseModel):
    rank: int
    text: str
    source: str
    score: float


class AskResponse(BaseModel):
    query: str
    answer: str
    citations: list[dict]
    cited_sources: list[str]


class UploadResponse(BaseModel):
    filename: str
    chunks_stored: int
    message: str


class StatsResponse(BaseModel):
    collection: str
    total_chunks: int
    embedding_model: str
    qdrant_url: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/healthz", tags=["system"])
async def health():
    """Liveness probe — no external dependencies."""
    return {"status": "ok", "service": "rag-framework", "version": "1.0.0"}


@app.get("/stats", response_model=StatsResponse, tags=["system"])
async def stats():
    """Return Qdrant collection statistics."""
    try:
        from rag.config import COLLECTION_NAME, EMBEDDING_MODEL, QDRANT_URL
        total = _get_store().count()
        return StatsResponse(
            collection=COLLECTION_NAME,
            total_chunks=total,
            embedding_model=EMBEDDING_MODEL,
            qdrant_url=QDRANT_URL,
        )
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"Qdrant unavailable: {exc}")


@app.post("/upload", response_model=UploadResponse, tags=["ingestion"])
async def upload_document(file: UploadFile = File(...)):
    """Upload and ingest a document into the vector store.

    Supported formats: PDF, TXT, Markdown, HTML.
    The file is chunked, embedded, and stored in Qdrant.
    The BM25 index is invalidated so the next search includes new chunks.
    """
    allowed = {".pdf", ".txt", ".md", ".html", ".htm",
               ".png", ".jpg", ".jpeg", ".gif", ".webp"}
    ext = Path(file.filename or "").suffix.lower()
    if ext not in allowed:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{ext}'. Allowed: {', '.join(sorted(allowed))}",
        )

    with tempfile.NamedTemporaryFile(delete=False, suffix=ext or ".tmp") as tmp:
        shutil.copyfileobj(file.file, tmp)
        tmp_path = tmp.name

    try:
        from rag.ingestion import IngestionPipeline
        pipeline = IngestionPipeline()
        embedder = _get_embedder()
        store = _get_store()

        chunks = pipeline.ingest_file(tmp_path)
        if not chunks:
            raise HTTPException(
                status_code=422, detail="No extractable content found in the file."
            )

        for chunk in chunks:
            chunk.source = file.filename  # preserve original filename

        embeddings = embedder.embed_texts([c.text for c in chunks])
        stored = store.upsert(chunks, embeddings)

        global _retriever
        _retriever = None  # invalidate BM25 index so next search picks up new chunks

        return UploadResponse(
            filename=file.filename,
            chunks_stored=stored,
            message=f"Successfully ingested {stored} chunks from '{file.filename}'.",
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    finally:
        os.unlink(tmp_path)


@app.post("/search", response_model=list[SearchResult], tags=["retrieval"])
async def search(request: SearchRequest):
    """Hybrid search (BM25 + vector + RRF) with cross-encoder reranking.

    Returns the top-k most relevant chunks, scored by the cross-encoder.
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    try:
        from rag.config import RERANK_FETCH_N
        retriever = _get_retriever()
        retriever.build_bm25_index_from_store()
        reranker = _get_reranker()

        candidates = [p for p, _ in retriever.search(request.query, top_k=RERANK_FETCH_N)]
        reranked = reranker.rerank(request.query, candidates, top_n=request.top_k)

        return [
            SearchResult(
                rank=i + 1,
                text=p["text"],
                source=p.get("source", "unknown"),
                score=round(score, 4),
            )
            for i, (p, score) in enumerate(reranked)
        ]
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=503, detail=str(exc))


@app.post("/ask-image", response_model=AskResponse, tags=["generation"])
async def ask_image(
    file: UploadFile = File(..., description="Image file (PNG, JPEG, GIF, WebP)"),
    query: str = Form(default="Describe what you see in this image."),
    top_k: int = Form(default=5),
    x_gemini_api_key: str | None = Header(
        default=None,
        alias="X-Gemini-API-Key"
    ),
):
    if not x_gemini_api_key or not x_gemini_api_key.strip():
        raise HTTPException(
            status_code=400,
            detail="Gemini API key is required. Add your key in Settings.",
        )
    """Answer a question about an uploaded image, grounded in the knowledge base.

    The image is sent directly to Gemini 2.0 Flash vision. Relevant text chunks
    from Qdrant are retrieved using the text query and included as context so
    Gemini can cross-reference the image with your indexed documents.
    """
    from rag.vision import SUPPORTED_IMAGE_EXTS, VisionAnalyzer

    ext = Path(file.filename or "").suffix.lower()
    if ext not in SUPPORTED_IMAGE_EXTS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Unsupported image type '{ext}'. "
                f"Supported: {', '.join(sorted(SUPPORTED_IMAGE_EXTS))}"
            ),
        )

    if not query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    image_bytes = await file.read()
    mime_type = SUPPORTED_IMAGE_EXTS[ext]

    try:
        from rag.config import RERANK_FETCH_N

        # Retrieve relevant text context using the text query
        context_chunks: list[dict] = []
        try:
            retriever = _get_retriever()
            retriever.build_bm25_index_from_store()
            reranker = _get_reranker()
            candidates = [p for p, _ in retriever.search(query, top_k=RERANK_FETCH_N)]
            if candidates:
                context_chunks = [
                    p for p, _ in reranker.rerank(query, candidates, top_n=top_k)
                ]
        except Exception:
            # Vector store unavailable — answer from image only, don't fail
            pass

        analyzer = VisionAnalyzer(api_key=x_gemini_api_key.strip())
        answer = analyzer.answer_about_image(
            image_bytes=image_bytes,
            mime_type=mime_type,
            query=query,
            context_chunks=context_chunks or None,
        )

        cited_sources = list(dict.fromkeys(
            c.get("source", "unknown") for c in context_chunks
        ))
        citations = [
            {"source": c.get("source", "unknown"), "text": c.get("text", "")[:200]}
            for c in context_chunks
        ]

        return AskResponse(
            query=query,
            answer=answer,
            citations=citations,
            cited_sources=cited_sources,
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=503, detail=str(exc))


@app.post("/ask", response_model=AskResponse, tags=["generation"])
async def ask(
    request: AskRequest,
    x_groq_api_key: str | None = Header(
        default=None,
        alias="X-Groq-API-Key"
    ),
):
    if not x_groq_api_key or not x_groq_api_key.strip():
        raise HTTPException(
            status_code=400,
            detail="Groq API key is required. Add your key in Settings.",
        )
    """Full RAG pipeline: hybrid retrieval → reranking → LLM with inline citations.

    Returns the generated answer with [N] citation markers and a deduplicated
    list of cited source filenames.
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    try:
        from rag.config import RERANK_FETCH_N, RERANK_TOP_N
        retriever = _get_retriever()
        retriever.build_bm25_index_from_store()
        reranker = _get_reranker()
        from rag.generator import Generator

        generator = Generator(
            provider="groq",
            api_key=x_groq_api_key.strip(),
        )

        candidates = [p for p, _ in retriever.search(request.query, top_k=RERANK_FETCH_N)]
        reranked_chunks = [
            p for p, _ in reranker.rerank(request.query, candidates, top_n=RERANK_TOP_N)
        ]
        result = generator.generate_with_citations(request.query, reranked_chunks)

        return AskResponse(
            query=result.query,
            answer=result.answer,
            citations=result.citations,
            cited_sources=result.cited_sources,
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=503, detail=str(exc))


@app.post("/stream", tags=["generation"])
async def stream_answer(
    request: AskRequest,
    x_groq_api_key: str | None = Header(
        default=None,
        alias="X-Groq-API-Key"
    ),
):
    if not request.query.strip():
            if not x_groq_api_key or not x_groq_api_key.strip():
                raise HTTPException(
                status_code=400,
                detail="Groq API key is required. Add your key in Settings.",
            )
    """Stream the RAG answer token-by-token using Server-Sent Events (SSE).

    Same retrieval pipeline as /ask (hybrid search → reranking → LLM), but
    the LLM response is streamed as it is generated rather than waiting for
    the full answer.

    SSE event format::

        data: {"type": "token",     "text": "Hello"}
        data: {"type": "citations", "citations": [...], "cited_sources": [...]}
        data: [DONE]

    The client should buffer token events to build the answer string and
    display the citations card only after the final [DONE] sentinel arrives.
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    # Snapshot request values so the closure captures plain strings, not the
    # Pydantic model, which avoids issues with generator / thread lifetimes.
    query = request.query
    top_k = request.top_k

    def event_generator():
        try:
            from rag.config import RERANK_FETCH_N, RERANK_TOP_N

            # --- retrieval (same as /ask) -----------------------------------
            context_chunks: list[dict] = []
            try:
                retriever = _get_retriever()
                retriever.build_bm25_index_from_store()
                reranker = _get_reranker()
                candidates = [p for p, _ in retriever.search(query, top_k=RERANK_FETCH_N)]
                if candidates:
                    context_chunks = [
                        p for p, _ in reranker.rerank(query, candidates, top_n=RERANK_TOP_N)
                    ]
            except Exception:
                # Qdrant unavailable — stream answer without context
                pass

            # --- stream tokens ----------------------------------------------
            from rag.generator import Generator

            generator = Generator(
                provider="groq",
                api_key=x_groq_api_key.strip(),
                )
            for token in generator.generate_stream(query, context_chunks):
                yield f"data: {json.dumps({'type': 'token', 'text': token})}\n\n"

            # --- citations metadata event (after all tokens) ----------------
            cited_sources = list(dict.fromkeys(
                c.get("source", "unknown") for c in context_chunks
            ))
            citations = [
                {"source": c.get("source", "unknown"), "text": c.get("text", "")[:200]}
                for c in context_chunks
            ]
            yield f"data: {json.dumps({'type': 'citations', 'citations': citations, 'cited_sources': cited_sources})}\n\n"

        except Exception as exc:
            yield f"data: {json.dumps({'type': 'error', 'message': str(exc)})}\n\n"

        finally:
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",   # disables nginx buffering if behind a proxy
            "Connection": "keep-alive",
        },
    )
